name: CustomCurrencies
version: '1.0.000-snapshot'
main: org.brentloaf.customCurrencies.CustomCurrencies
api-version: '1.21'
commands:
  add_vault:
    usage: /add_vault <currency_name>
  get_currency:
    usage: /get_currency <currency_name>
  get_currency_value:
    usage: /get_currency_value <currency_name>
  create_currency:
    usage: /create_currency <currency_name> <material>
  create_bank:
    usage: /create_bank <bank_name> <coin_material> <crafting_materials>

